export const SET_CUSTOMERS = 'SET_CUSTOMERS';

export const SET_CUSTOMER = 'SET_CUSTOMER';

export const SET_CUSTOMER_FIELD = 'SET_CUSTOMER_FIELD';

export const SET_NEW_CUSTOMER = 'SET_NEW_CUSTOMER';

export const SET_NEW_CUSTOMER_FIELD = 'SET_NEW_CUSTOMER_FIELD';
